// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnMsJWcdlf7LqJ3l_95zLi8vAM6YqSSs',
    appId: '1:960946356186:web:9aec6f0a344f52d405cae3',
    messagingSenderId: '960946356186',
    projectId: 'lab3-f9683',
    authDomain: 'lab3-f9683.firebaseapp.com',
    storageBucket: 'lab3-f9683.firebasestorage.app',
    measurementId: 'G-N1X7TCXSXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7BH9cduF0hHfkgF9NW9TMnaOI1HjMn8',
    appId: '1:960946356186:android:d538b077ba1afe7105cae3',
    messagingSenderId: '960946356186',
    projectId: 'lab3-f9683',
    storageBucket: 'lab3-f9683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoav4IvAx5eTmsMr4aZuY0WmKhWwg8A-I',
    appId: '1:960946356186:ios:085a5f65d827869a05cae3',
    messagingSenderId: '960946356186',
    projectId: 'lab3-f9683',
    storageBucket: 'lab3-f9683.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoav4IvAx5eTmsMr4aZuY0WmKhWwg8A-I',
    appId: '1:960946356186:ios:085a5f65d827869a05cae3',
    messagingSenderId: '960946356186',
    projectId: 'lab3-f9683',
    storageBucket: 'lab3-f9683.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPnMsJWcdlf7LqJ3l_95zLi8vAM6YqSSs',
    appId: '1:960946356186:web:8ab810683e7f5d2105cae3',
    messagingSenderId: '960946356186',
    projectId: 'lab3-f9683',
    authDomain: 'lab3-f9683.firebaseapp.com',
    storageBucket: 'lab3-f9683.firebasestorage.app',
    measurementId: 'G-DJ7KWE5LEN',
  );
}
